# Generated by Django 4.1.5 on 2023-01-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propTitle', models.CharField(max_length=100)),
                ('propDescription', models.CharField(max_length=700)),
                ('propDetails', models.CharField(max_length=500)),
                ('propLocation', models.CharField(max_length=100)),
                ('propImage', models.ImageField(upload_to='images/')),
                ('amount', models.FloatField()),
                ('minInvest', models.FloatField()),
                ('maxInvest', models.FloatField()),
                ('returnRate', models.CharField(max_length=50)),
                ('capital', models.CharField(max_length=50)),
            ],
        ),
    ]
