# Generated by Django 4.1.5 on 2023-01-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_investments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplans',
            name='propDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='investmentplans',
            name='propDetails',
            field=models.TextField(),
        ),
    ]
